FROM openjdk:17-jdk-buster

ARG DEPLOY_VERSION="app"

COPY entrypoint.sh ./
COPY build/libs/${DEPLOY_VERSION}.jar app.jar

ARG DB_HOST
ARG DB_PASSWORD
ARG DB_USERNAME
ARG DEFAULT_DATABASE
ARG SMTP_EMAIL
ARG SMTP_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_USERNAME=$DB_USERNAME
ENV DEFAULT_DATABASE=$DEFAULT_DATABASE
ENV SMTP_EMAIL=$SMTP_EMAIL
ENV SMTP_PASSWORD=$SMTP_PASSWORD

ENTRYPOINT ["bash","/entrypoint.sh"]
