spring:
  r2dbc:
    url: r2dbc:mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:3306/${DEFAULT_DATABASE}
    properties:
      ssl: true
      sslMode: VERIFY_IDENTITY

  application:
    name: realtime-search-server

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
      base-path: "/"

server:
  port: 8080
